server.port=8080

# Outlook/Exchange Configuration
outlook.email=22701a3101@aitsrajampet.ac.in
outlook.password=Aga@54321
outlook.exchange-url=https://outlook.cloud.microsoft/mail/

# Logging
logging.level.root=INFO
logging.level.com.example.emailservice=DEBUG