server.port=8080

# EWS (Exchange Web Services) Configuration
# Used for basic authentication with Exchange Online / Office 365
outlook.email=22701a3101@aitsrajampet.ac.in
outlook.password=Aga@54321
# EWS endpoint for Exchange Online / Office 365
outlook.exchange-url=https://outlook.office365.com/ews/exchange.asmx

# Logging
logging.level.root=INFO
logging.level.com.example.emailservice=DEBUG